### ISSUE TITLE
Join Leave Logs

### ISSUE THREAD

**Issue by tTinted** [InsanityBot/insanitybot-v2#10]
There is a bug with Discord Mobile which does not display mentions of users who have left the server properly. Therefore it should be considered to have insanitybot both support Mentions and Username#Discriminator format in join-leave log messages.

**Comment by TrainerGamer** [comment]
No, InsanityMod now sends join leave messages. These work properly. However, I can add it to show `Wumpus#0000` rather than their user ID.

**Comment by tTinted** [comment]
Ok please do. Maybe it is my discord being idiotic again.

**Comment by TrainerGamer** [comment]
No, it's broken at my end too once I reload Discord. I'll fix it...

**Comment by akiraveliara** [comment]
@TrainerGamer @tTinted Please keep issues and discussions as generic as possible and not related to a specific discord server. I will now edit the main issue to be as generic as required.

Yes, it is possible to add a config option to either mention or use the format Username#Discriminator in the log message.
