### ISSUE TITLE
Configurable Ticket Presets

### ISSUE THREAD

**Issue by tTinted** [InsanityBot/insanitybot-v2#11]
**Is your feature request related to a problem? Please describe.**
For things like demote tickets its annoying to be pinged, when it really is a 1 on 1 conversation.

**Describe the solution you'd like**
A new command that creates a ticket that does not ping people.

**Describe alternatives you've considered**

**Additional context**
Command could be something like i.ticket management noping

**Comment by akiraveliara** [comment]
Flags for certain commands - such as "i.ticket management -noping" are an interesting idea... any more information on this?

**Comment by tTinted** [comment]
Yes we could do i.ticket management -add <@ID> instead of adding them within the ticket.
I think you should be able to so multiple flags in 1 command aswell, like i.ticket management -noping -add <@ID> -add <@ID>

There could also be one like have insanity bot immediatly send a message with a few words such as i.ticket management -noping -add <@ID> -say This is a demote ticket for ---.

If i think of others I will add more replies.

**Comment by akiraveliara** [comment]
The last idea seems like more a matter for Ticket Presets...
<code>"presets.<name>.ticket_creation_message": "This is a demote ticket for {position}"</code>

**Comment by tTinted** [comment]
O ye

**Comment by akiraveliara** [comment]
Scheduling this for 2.0.0-beta.002 as a confirmed feature

**Comment by akiraveliara** [comment]
implemented with #93, easier interaction with the system is in the works

**Comment by akiraveliara** [comment]
implemented. control via discord will be added by the next dev release
