### ISSUE TITLE
Whitelist that bypasses i.lock




### ISSUE THREAD

**Issue by NotWellard** [InsanityBot/insanitybot-v2#41]
So `i.whitelist mention/id/name` would whitelist a person allowing them all their normal permissions in a locked channel. Useful for moderation. Obviously there would be `i.unwhitelist` to go along with it.

**Comment by akiraveliara** [comment]
This would probably have to be done via a special role like muted/blacklisted, just inversed
Channel locking is scheduled for release by beta-002 so i'll look into a fast implementation for this

**Comment by akiraveliara** [comment]
Implemented in [993c1be](https://github.com/InsanityNetwork/InsanityBot/commit/993c1be8d1602abed160723db3174ad2870f2d99). Control functionality will be added in upcoming commits.
