### ISSUE TITLE
Spelling error in pull request template

### ISSUE THREAD

**Issue by akiraveliara** [InsanityBot/insanitybot-v2#45]
Spelling mistake in the pull request template

affects:
InsanityNetwork/InsanityBot/master@035510b (latest)
InsanityNetwork/InsanityBot/2.0.0-dev@2c0c448 (latest)

**Comment by TrainerGamer** [comment]
May I ask what spelling errors there are?

**Comment by TrainerGamer** [comment]
@ExaInsanity Please open a PR for any updates you want done to any of the files.

**Comment by ExaInsanity** [comment]
closed by #46

**Comment by TrainerGamer** [comment]
Fixed in #46
