### ISSUE TITLE
Add news of different kinds like covid and weather and current situation about a country and make it auto every 24 hours 

### ISSUE THREAD

**Issue by ghost** [InsanityBot/insanitybot-v2#49]
**Describe the idea you'd like to see impplemented**

**Describe alternatives you've considered**

**Additional context**

**Comment by akiraveliara** [comment]
Please actually use the description and don't just put everything in the title

**Comment by NoobChester** [comment]
oof

**Comment by TrainerGamer** [comment]
Use #50 for this feature request
