### ISSUE TITLE
Pi command

### ISSUE THREAD

**Issue by Pi-Cat** [InsanityBot/insanitybot-v2#54]
Pi command

Pi command
 
 it says pi

**Comment by TrainerGamer** [comment]
What practical use would this command have?

**Comment by Pi-Cat** [comment]
saying pi

**Comment by TrainerGamer** [comment]
So `i.pi` would just make the bot say `pi`?

**Comment by Pi-Cat** [comment]
or 3.14159265...

**Comment by TrainerGamer** [comment]
This has no practical use and I can't see Exa adding it just as a joke (she only likes her bot to be practical).

If the tag system is on 2.0 you would be able to do this with tags, but not as a standalone command.

**Comment by Pi-Cat** [comment]
sad
