### ISSUE TITLE
Verbal log retrieval error

### ISSUE THREAD

**Issue by NotWellard** [InsanityBot/insanitybot-v2#68]
**Describe the bug**
Verballog command doesn't work

**To Reproduce**
Type i.verballog user

**Expected behaviour**
It shows the verbal log

**Screenshots**
If applicable, add screenshots to help explain your [**exa**mple of it not working](https://user-images.githubusercontent.com/46070406/114420759-82702580-9bac-11eb-8489-c26f810bab7b.jpg)

**Host system (please complete the following information):**
 OS: windows 10 build 2004
Bot version: e136907

**Comment by akiraveliara** [comment]
cannot reproduce with 2.0.0-dev.00022, neither on linux mint with e136907

**Comment by akiraveliara** [comment]
fixed in the next commit
