### ISSUE TITLE
A seperate channel that logs all messages, but it only viewable by management. This would help if people are trolling in tickets, or if a staff deletes half the things they say.

### ISSUE THREAD

**Issue by tTinted** [InsanityBot/insanitybot-v2#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akiraveliara** [comment]
Please describe your issue more precise and instead cut down the title length.

**Comment by akiraveliara** [comment]
specified in #8
