### ISSUE TITLE
Modlog moderation count per category

### ISSUE THREAD

**Issue by NoobChester** [InsanityBot/insanitybot-v2#72]
Count the amount of warns, verbal warns, temp-bans, etc.
Preferably at the start of the Modlog embed.
The current display system through the i.modlog command is just very unintuitive, especially when the Modlog grows.

**Comment by akiraveliara** [comment]
Generally the modlog frontend needs a rework, such as the capability to only display certain types.
As for tempbans, @NoobChester the bot does not differentiate between bans and tempbans

**Comment by akiraveliara** [comment]
We need a more stable interactivity backend before doing any work on the modlog frontend though, so don't expect this anytime soon.

**Comment by akiraveliara** [comment]
Implemented as of d4c7cf0
