### ISSUE TITLE
Embed fields

### ISSUE THREAD

**Issue by Zefyro** [InsanityBot/insanitybot-v2#77]
**Describe the idea you'd like to see implemented**
embed fields for `i.embed` command which allows the ability to set the embed's `Title`, `Field(s)`, `Description`, `Footer` & other stuff like that. 

**Additional context**
This would make the embed command more useful imo.

**Comment by akiraveliara** [comment]
Please see whether the attached [syntax specification](https://github.com/InsanityBot/insanitybot/files/6511115/embed-command-syntax.md) achieves everything it needs to

**Comment by Zefyro** [comment]
> Please see whether the attached [syntax specification](https://github.com/InsanityBot/insanitybot/files/6511115/embed-command-syntax.md) achieves everything it needs to

I feel like full json format would be easier but that does achieve everything it needs to as far as I can see with a quit glance.

**Comment by akiraveliara** [comment]
[This](https://github.com/InsanityBot/insanitybot/files/6514082/embed-command-syntax.md) new specification supports everything we need and includes the names. The issue with the previous specification was that there was no way to tell whether a whitespace was part of a passed string (`title:I am here`) or intending to separate two entries (`title:Hi description:Hello`).

Please review this specification.

**Comment by Zefyro** [comment]
Looks good, now I don't any issues with that. :)
