### ISSUE TITLE
Multi-log support

### ISSUE THREAD

**Issue by tTinted** [InsanityBot/insanitybot-v2#8]
**Is your feature request related to a problem? Please describe.**
We have stopped logging tickets and staff chat to avoid leaking, but I think we should still log them, just prevent them from leaking

**Describe the solution you'd like**
I think if we made a 2nd message logs channel, and only management could view it, this problem would be amazing fixed. Nothing would be leaked, since management can already see everything, and we still would know if we have a bad staff or something ticket trolling.

**Describe alternatives you've considered**
Go back to original since leaking wasn't even really a problem.

**Additional context**
Was it really necessary that I make a github account to do this, and not just suggest it in the discord?

**Comment by akiraveliara** [comment]
Please keep feature requests as generic as possible - as in, the more people's discord implementations can benefit from it, the better. 
Yes, it was necessary to make a github account for this as this is a suggestion for InsanityBot 2.0 which is managed via github only.

I think what you are essentially suggesting on the bot side is support for multiple logging channels which would furthermore be configurable to only log certain categories/channels?

**Comment by tTinted** [comment]
ok

**Comment by akiraveliara** [comment]
Confirmed.

**Comment by akiraveliara** [comment]
Implemented with #85
