### ISSUE TITLE
Allow pruning messages until message ID found

### ISSUE THREAD

**Issue by Excigma** [InsanityBot/insanitybot-v2#81]
**Describe the idea you'd like to see implemented**
A command that will prune all messages after the message ID passed with the command.

Plausible way it will work:
- Checks if there is actually a message with that ID and that it isn't too old (prevent raiding using this?)
- Delete all messages after that message

**Describe alternatives you've considered**
Not being lazy and count the messages to prune, then pruning them

**Comment by akiraveliara** [comment]
Good suggestion, but currently impossible with InsanityBot's flawed backend. When that is taken care of, we will reevaluate the suggestion 🙂

**Comment by akiraveliara** [comment]
implemented with fb43ec0

**Comment by akiraveliara** [comment]
closed with #99
