### ISSUE TITLE
Modlog spam (I guess)

### ISSUE THREAD

**Issue by Zefyro** [InsanityBot/insanitybot-v2#91]
**Describe the bug**
When tempmute period is over the bot starts to spam in the mod log channel.

**To Reproduce**
Download the `2.0.0-dev.00033` pre release version of the bot, set it up & temp mute someone for *x* amount of time.
`admin.tempmute 349598495264735233 5s` (my ID)
and wait the for the mute to end.

**Expected behaviour**
The bot should send the following embed messages once. (When running the command)
![image](https://user-images.githubusercontent.com/71092443/123546902-412cf200-d767-11eb-9bf8-8d7bff6f0a56.png)
(After the timer runs out.)
![image](https://user-images.githubusercontent.com/71092443/123546930-5a35a300-d767-11eb-9547-f6c90ba21b09.png)

**Screenshots**
The bot starts to spam the `UNMUTE` embed message
![image](https://user-images.githubusercontent.com/71092443/123546849-0fb42680-d767-11eb-887d-967a68452d06.png)

**Host system (please complete the following information):**
 - Bot version [2.0.0-dev.00033]

**Additional context**
Its kinda funny how it works ;P

**Comment by ExaInsanity** [comment]
Can you provide your cache/timers/192e3b0f-649b-4738-8f6a-7c45b1bcffd9 file?

**Comment by akiraveliara** [comment]
Can confirm, the timer is never unregistered and therefore keeps being processed.

**Comment by akiraveliara** [comment]
fixed in 7e46bff8db58281c044bdfd57c1b64c35c89d749
